#pragma once

#include <Config/keys/hardware.h>

#define CONF_HW_MOTORS_DEFAULT        "motors"
#define CONF_HW_CAMERAS_DEFAULT       "cameras"
#define CONF_HW_FORCE_SENSORS_DEFAULT "forceSensors"

// MOTORS
// --- Common
#define CONF_HW_SCREW_PITCH_MM_DEFAULT         0.0
#define CONF_HW_MAX_VELOCITY_MM_S_DEFAULT      0.0
#define CONF_HW_MAX_ACCELERATION_MM_S2_DEFAULT 0.0
// --- With encoder
#define CONF_HW_ENCODER_TOPS_PER_REV_DEFAULT 0
// --- Steppers
#define CONF_HW_MOTOR_STEPS_PER_REV_DEFAULT 0
// --- Direct current
#define CONF_HW_MOTOR_MAX_POSITIVE_TORQUE_DEFAULT 100
#define CONF_HW_MOTOR_MAX_NEGATIVE_TORQUE_DEFAULT 100

// CAMERAS
#define CONF_HW_MAX_EXPOSURE_US_DEFAULT     50000.0
#define CONF_HW_DEFAULT_EXPOSURE_US_DEFAULT 5000.0
#define CONF_HW_MAX_GAIN_DB_DEFAULT         24.0
#define CONF_HW_DEFAULT_GAIN_DB_DEFAULT     2.0
#define CONF_HW_FRAMERATE_DEFAULT           30.0

// LOCALE
#define CONF_HW_LOCALE_DEFAULT LOCALE_EN_US
