#pragma once

// CONF_PROCESS_KINEMATICS
#define CONF_PROCESS_TARGET_VELOCITY_MM_S_DEFAULT 0.0
#define CONF_PROCESS_ACCELERATION_MM_S_DEFAULT    0.0
// --- Steppers
#define CONF_PROCESS_STEP_FRACTION_DEFAULT 1

// CONF_PROCESS_CAMERAS
#define CONF_PROCESS_MIN_CAMERA_DISTANCE_MM_DEFAULT           50.0
#define CONF_PROCESS_LEFT_CAM_X_RESET_POS_MM_DEFAULT          0.0
#define CONF_PROCESS_LEFT_CAM_Y_RESET_POS_MM_DEFAULT          0.0
#define CONF_PROCESS_RIGHT_CAM_X_RESET_POS_MM_DEFAULT         0.0
#define CONF_PROCESS_RIGHT_CAM_Y_RESET_POS_MM_DEFAULT         0.0
#define CONF_PROCESS_LEFT_CAM_X_HOME_POS_MM_DEFAULT           0.0
#define CONF_PROCESS_LEFT_CAM_Y_HOME_POS_MM_DEFAULT           0.0
#define CONF_PROCESS_RIGHT_CAM_X_HOME_POS_MM_DEFAULT          0.0
#define CONF_PROCESS_RIGHT_CAM_Y_HOME_POS_MM_DEFAULT          0.0
#define CONF_PROCESS_LEFT_CAM_X_VIRTUAL_LIMIT_POS_MM_DEFAULT  0.0
#define CONF_PROCESS_RIGHT_CAM_X_VIRTUAL_LIMIT_POS_MM_DEFAULT 0.0
// Focals
#define CONF_PROCESS_FOCAL_DEFAULT_VALUE_DEFAULT 0
#define CONF_PROCESS_FOCAL_MIN_VALUE_DEFAULT     0
#define CONF_PROCESS_FOCAL_MAX_VALUE_DEFAULT     4095

// CONF_PROCESS_ELEVATOR_POSITIONS
#define CONF_PROCESS_MAX_Z_RELATIVE_DISTANCE_MM_DEFAULT 10.0

// CONF_PROCESS_ALIGNMENT_POSITIONS
#define CONF_PROCESS_X_STAGE_CENTER_POS_MM_DEFAULT     0.0
#define CONF_PROCESS_Y_STAGE_CENTER_POS_MM_DEFAULT     0.0
#define CONF_PROCESS_THETA_STAGE_CENTER_POS_MM_DEFAULT 0.0

// CONF_PROCESS_DRAWERS_POSITIONS
#define CONF_PROCESS_CM3_RESET_POS_MM_DEFAULT              0.0
#define CONF_PROCESS_MASK_CONV_EJECT_DECEL_POS_MM_DEFAULT  100.0
#define CONF_PROCESS_WAFER_CONV_EJECT_DECEL_POS_MM_DEFAULT 100.0

// CONF_PROCESS_FORCE_LIMITS
#define CONF_PROCESS_CONTACT_THRESHOLD_GF_DEFAULT         50.0
#define CONF_PROCESS_AUTOLEVEL_FORCE_GF_DEFAULT           500.0
#define CONF_PROCESS_AUTOLEVEL_FORCE_TOLERANCE_GF_DEFAULT 50.0
#define CONF_PROCESS_MAX_FORCE_GF_DEFAULT                 4000.0
#define CONF_PROCESS_HW_CRASH_FORCE_LIMIT_GF_DEFAULT      8000.0

// CONF_PROCESS_ADMITTANCE_TUNING
#define CONF_PROCESS_ADMITTANCE_MAX_STEP_MM_PER_TICK_DEFAULT        0.25
#define CONF_PROCESS_ADMITTANCE_DEADBAND_VELOCITY_MM_S_DEFAULT      0.001
#define CONF_PROCESS_ADMITTANCE_TRANSLATION_GAIN_LOW_FORCE_DEFAULT  1.0
#define CONF_PROCESS_ADMITTANCE_TRANSLATION_GAIN_HIGH_FORCE_DEFAULT 0.00015
#define CONF_PROCESS_ADMITTANCE_ROTATION_GAIN_LOW_FORCE_DEFAULT     0.8
#define CONF_PROCESS_ADMITTANCE_ROTATION_GAIN_HIGH_FORCE_DEFAULT    0.00015

// CONF_PROCESS_PAD_MOVEMENTS
#define CONF_PROCESS_X_STAGE_DISTANCE_MM_DEFAULT        0.001
#define CONF_PROCESS_Y_STAGE_DISTANCE_MM_DEFAULT        0.001
#define CONF_PROCESS_THETA_STAGE_DISTANCE_MM_DEFAULT    0.001
#define CONF_PROCESS_Z_MOTORS_DISTANCE_MM_DEFAULT       0.1
#define CONF_PROCESS_LEFT_CAM_X_DISTANCE_MM_DEFAULT     1.0
#define CONF_PROCESS_RIGHT_CAM_X_DISTANCE_MM_DEFAULT    1.0
#define CONF_PROCESS_LEFT_CAM_Y_DISTANCE_MM_DEFAULT     1.0
#define CONF_PROCESS_RIGHT_CAM_Y_DISTANCE_MM_DEFAULT    1.0
#define CONF_PROCESS_LEFT_CAM_LIGHTING_STEP_PC_DEFAULT  1.0
#define CONF_PROCESS_RIGHT_CAM_LIGHTING_STEP_PC_DEFAULT 1.0
#define CONF_PROCESS_LEFT_CAM_FOCAL_STEP_PC_DEFAULT     1.0
#define CONF_PROCESS_RIGHT_CAM_FOCAL_STEP_PC_DEFAULT    1.0
