#pragma once

#define EMERGENCY_STOP "emergencyStop"

#define WAFER_ENCODER   "waferDrawerEncoderPosition"
#define MASK_ENCODER    "maskDrawerEncoderPosition"
#define Z_LEFT_ENCODER  "zLeftEncoderPosition"
#define Z_RIGHT_ENCODER "zRightEncoderPosition"
#define Z_BACK_ENCODER  "zBackEncoderPosition"

#define Z_LEFT_HIGH_LIMIT  "zLeftHighLimit"
#define Z_LEFT_LOW_LIMIT   "zLeftLowLimit"
#define Z_RIGHT_HIGH_LIMIT "zRightHighLimit"
#define Z_RIGHT_LOW_LIMIT  "zRightLowLimit"
#define Z_BACK_HIGH_LIMIT  "zBackHighLimit"
#define Z_BACK_LOW_LIMIT   "zBackLowLimit"
#define CM0                "maskCM0Limit"
#define CM1                "maskCM1Limit"
#define CM2                "maskCM2Limit"
#define CM3                "maskCM3Limit"
#define CW0                "waferCW0Limit"
#define CW1                "waferCW1Limit"
#define CW2                "waferCW2Limit"
#define Z1                 "z1Limit"
#define WAFER_ON           "waferOnLimit"
#define Z2                 "z2Limit"

#define FORCE_LEFT     "leftForceSensor"
#define FORCE_RIGHT    "rightForceSensor"
#define FORCE_BACK     "backForceSensor"
#define FORCE_LEFT_EN  "leftForceSensorEnabled"
#define FORCE_RIGHT_EN "rightForceSensorEnabled"
#define FORCE_BACK_EN  "backForceSensorEnabled"

#define MASK_VACUUM_VALVE          "maskVacuumValveStatus"
#define WAFER_VACUUM_VALVE         "waferVacuumValveStatus"
#define WAFER_COMPRESSED_AIR_VALVE "waferCompressedAirValveStatus"

#define MASK_VACUUM_ACTIVE          "maskVacuumActive"
#define WAFER_VACUUM_ACTIVE         "waferVacuumActive"
#define WAFER_COMPRESSED_AIR_ACTIVE "waferCompressedAirActive"
